# Generated by Django 5.0.1 on 2024-03-21 23:47

import django.db.models.deletion
import enumfields.fields
import gerenciamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('pais', models.CharField(max_length=255)),
                ('estado', enumfields.fields.EnumField(enum=gerenciamento.models.EstadoEnum, max_length=2)),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=40)),
                ('numero_casa', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_estado', enumfields.fields.EnumField(enum=gerenciamento.models.EstadoEnum, max_length=2)),
                ('crm_digito', models.CharField(max_length=6)),
                ('especialidade', models.CharField(max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('consulta', models.ManyToManyField(blank=True, null=True, related_name='consulta_medico', to='gerenciamento.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_consulta', to='gerenciamento.medico', verbose_name='medico_consulta'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=255, unique=True)),
                ('consulta', models.ManyToManyField(blank=True, null=True, related_name='consulta_paciente', to='gerenciamento.consulta')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_paciente', to='gerenciamento.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_paciente', to='gerenciamento.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_consulta', to='gerenciamento.paciente', verbose_name='paciente_consulta'),
        ),
    ]
