# Generated by Django 5.0.1 on 2024-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
