# Generated by Django 5.0.1 on 2024-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_coordenador_password_paciente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='codigo_sus',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
