# Generated by Django 5.0.4 on 2024-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_paciente_codigo_sus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='consulta',
            field=models.ManyToManyField(null=True, related_name='consulta_paciente', to='gerenciamento.consulta'),
        ),
    ]
